server:
  port: 7070
spring:
  resources:
    static-locations: classpath:/static/
  profiles:
    active: dev
  datasource:
    db1:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://10.18.9.20:3306/db1?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimeZone=GMT
      username: office
      password: 123456
    db2:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://10.18.9.20:3306/db2?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimeZone=GMT
      username: office
      password: 123456
  freemarker:
    template-loader-path: classpath:/templates
    suffix: .ftl
    cache: false
    charset: UTF-8
    settings:
      classic_compatible: true
      default_encoding: UTF-8
      template_update_delay: 0
mybatis:
  mapperLocations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  config: classpath:logback-${spring.profiles.active}.xml
  level:
    org:
      gary:
        webproject:
          mapper: debug


